services:
  - type: web
    name: project-nexus
    plan: free
    docker:
      dockerfile: backend/Dockerfile
      context: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project-nexus-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: project-nexus-db
    plan: free